from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from agent.graph import build_graph, chat_model
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage

# ลบ chat_memory_store ออกไปเลย! เราจะใช้ความจำจาก Open WebUI แทน

app = FastAPI()

# ----- เพิ่ม CORS Middleware เพื่อให้ Open WebUI ยิง API เข้ามาได้ -----
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], 
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

graph = build_graph()

# ---------- OpenAI-compatible schema ----------
class Message(BaseModel):
    role: str
    content: str

class ChatRequest(BaseModel):
    model: str
    messages: list[Message]

@app.post("/v1/chat/completions")
async def chat_completions(req: ChatRequest):
    
    # 1. Convert Open WebUI messages to LangGraph message format
    langchain_messages = []
    for msg in req.messages:
        if msg.role == "user":
            langchain_messages.append(HumanMessage(content=msg.content))
        elif msg.role == "assistant":
            langchain_messages.append(AIMessage(content=msg.content))
        elif msg.role == "system":
            langchain_messages.append(SystemMessage(content=msg.content))

    # Intercept background tasks generated by Open WebUI to prevent them from entering the graph
    last_message_content = req.messages[-1].content if req.messages else ""
    
    is_webui_task = any(keyword in last_message_content for keyword in [
        "Generate a concise, 3-5 word title",
        "Generate 1-3 broad tags",
        "Suggest 3-5 relevant follow-up questions"
    ])

    usage_data = {
        "prompt_tokens": 0,
        "completion_tokens": 0,
        "total_tokens": 0
    }

    if is_webui_task:
        print("\n[Interceptor] Open WebUI automated task detected. Bypassing LangGraph.")
        # Call the model directly without saving to memory
        response = chat_model.invoke(langchain_messages)
        assistant_content = response.content
        
        # Extract token usage for the automated task
        meta = getattr(response, "usage_metadata", {}) or {}
        usage_data["prompt_tokens"] = meta.get("input_tokens", 0)
        usage_data["completion_tokens"] = meta.get("output_tokens", 0)
        usage_data["total_tokens"] = meta.get("total_tokens", 0)
        
    else:
        print("\n[Interceptor] Normal user message detected. Routing to LangGraph.")
        # 2. Pass the entire history into LangGraph
        result = graph.invoke({
            "messages": langchain_messages,
            "steps": [],
            "current_node": "",
            "intent": None
        })

        # 3. Retrieve the final response from AI
        assistant_msg = result["messages"][-1]
        assistant_content = assistant_msg.content

        # Extract token usage for the normal chat
        meta = getattr(assistant_msg, "usage_metadata", {}) or {}
        usage_data["prompt_tokens"] = meta.get("input_tokens", 0)
        usage_data["completion_tokens"] = meta.get("output_tokens", 0)
        usage_data["total_tokens"] = meta.get("total_tokens", 0)

    # 4. Return the response to Open WebUI
    return {
        "id": "chatcmpl-health",
        "object": "chat.completion",
        "choices": [
            {
                "index": 0,
                "message": {
                    "role": "assistant",
                    "content": assistant_content
                },
                "finish_reason": "stop"
            }
        ],
        "usage": usage_data
    }

@app.get("/v1/models")
async def list_models():
    return {
        "object": "list",
        "data": [
            {
                "id": "health-model",  # ชื่อที่คุณต้องการให้โผล่ใน Open WebUI
                "object": "model",
                "created": 1667925528,
                "owned_by": "health-chatbot"
            }
        ]
    }